export const sliderItems = [
  {
    id: 1,
    img: "./assets/images/model2.png",
    title: "AUTUMN COLLECTION",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "#fcf1ed",
    circle: "#2F3C7E",
  },

  {
    id: 2,
    img: "./assets/images/model3.png",
    title: "LOUNGEWEAR LOVE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "#fbf0f4",
    circle: "#990011FF",
  },
  {
    id: 3,
    img: "./assets/images/model1.png",
    title: "SUMMER SALE",
    desc: "DON'T COMPROMISE ON STYLE! GET FLAT 30% OFF FOR NEW ARRIVALS.",
    bg: "#f5fafd",
    circle: "#fff",
  },
];

export const categories = [
  {
    id: 1,
    img: "./assets/images/cate1.png",
    title: "SHIRT STYLE!",
  },
  {
    id: 2,
    img: "./assets/images/cate2.png",
    title: "LOUNGEWEAR LOVE",
  },
  {
    id: 3,
    img: "./assets/images/cate3.png",
    title: "LIGHT JACKETS",
  },
  {
    id: 4,
    img: "./assets/images/cate4.png",
    title: "LEATHER PANT",
  },
  {
    id: 5,
    img: "./assets/images/cate5.png",
    title: "EARING STYLE",
  },
];

export const popularProducts = [
  {
    id: 1,
    img: "https://d3o2e4jr3mxnm3.cloudfront.net/Mens-Jake-Guitar-Vintage-Crusher-Tee_68382_1_lg.png",
    name: "Guitar Shirt",
    price: 1000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis itaque rerum delenitiiste, excepturi illo! Dolore omnis, eaque nobis cumque doloremque",
    size: "Large",
    color: "Tan",
    quan: 1,
  },
  {
    id: 2,
    img: "./assets/images/product2.png",
    name: "Vintage 90s Nike Jacket",
    price: 8000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis itaque rerum delenitiiste, excepturi illo! Dolore omnis, eaque nobis cumque assumenda eosprovident unde minus, eligendi delectus id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe doloremque s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe",
    size: "Medium",
    color: "Black",
    quan: 1,
  },
  {
    id: 3,
    minImg: "./assets/images/minProduct3.png",
    img: "./assets/images/product3.png",
    name: "Starter Jacket",
    price: 4000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitae delenitiiste, excepturi illo! Dolore omnis, eaque nobis cumque assumenda eosprovident unde minus, eligendi delectus id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe doloremque",
    size: "Medium",
    color: "Black-White",
    quan: 1,
  },
  {
    id: 4,
    img: "./assets/images/product4.png",
    name: "Leather Jacket",
    price: 6000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis itaque rerum delenitiiste, excepturi illo! Dolore omnis, eaque nobis cumque assumenda eosprovident unde minus, eligendi delectus id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe doloremque s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe",
    size: "X-Larger",
    color: "Faded Black",
    quan: 1,
  },
  {
    id: 5,
    img: "./assets/images/product5.png",
    name: "Layer Vintage Sweater",
    price: 3000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet obis cumque assumenda eosprovident unde minus, eligendi delectus id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe doloremque",
    size: "Small",
    color: "Black",
    quan: 1,
  },
  {
    id: 6,
    img: "./assets/images/product1.png",
    name: "Scooby-Doo Sweater",
    price: 1000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis itaque rerum delenitiiste, excepturi illo! Dolore omnis, eaque nobis cumque assumenda eosprovident unde minus, eligendi delectus id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe doloremque s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe",
    size: "Medium",
    color: "Navy",
    quan: 1,
  },
  {
    id: 7,
    img: "./assets/images/product6.png",
    name: "Leather Jacket",
    price: 7000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiisipisci reprehenderit voluptatevoluptate saepe doloremque",
    size: "Large",
    color: "Black",
    quan: 1,
  },
  {
    id: 8,
    img: "./assets/images/product7.png",
    name: "Bluebery Coat",
    price: 10000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis itaque rerum delenitiiste, excepturi illo! Dolore omnis, eaque nobis cumque assumenda eosprovident unde minus, eligendi delectus id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe doloremque s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe",
    size: "Medium",
    color: "Tan",
    quan: 1,
  },
];

export const products = [
  {
    id: 9,
    img: "./assets/images/pro1.png",
    name: "Chanel Sweater",
    price: 8000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis itaque rerum delenitiiste, excepturi illo! Dolore omnis, eaque nobis cumque assumenda eosprovident unde minus, eligendi dipisci reprehenderit voluptatevoluptate saepe s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe",
    size: "Medium",
    color: "Navy",
    quan: 1,
  },
  {
    id: 10,
    img: "./assets/images/pro2.png",
    name: "Vintage JP Jacket",
    price: 6000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis iationeadipisci reprehenderit voluptatevoluptate saepe doloremque s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe",
    size: "Larger",
    color: "Olive",
    quan: 1,
  },
  {
    id: 11,
    img: "./assets/images/pro3.png",
    name: "Avirex USA",
    price: 12000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis itaque rerum delenitiiste, excepturi illo! Doadipisci reprehenderit voluptatevoluptate saepe doloremque s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe",
    size: "Small",
    color: "White",
    quan: 1,
  },
  {
    id: 12,
    img: "./assets/images/pro4.png",
    name: "Carhartt Jacket",
    price: 8000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis itaque rerum delenitiiste, excepturi illo! Dolore omnis, eaque nobis cumque assumenda eosprovident unde minus, eligendi voluptate saepe s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe",
    size: "Small",
    color: "Red",
    quan: 1,
  },
  {
    id: 13,
    img: "./assets/images/pro5.png",
    name: "Vintage Uniqlo Puffe",
    price: 8000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis itaque rerum delenitiiste, excepturi illo! Dolore omnis, eaque nobis cumque assumelat, rationeadipisci reprehenderit voluptatevoluptate saepe doloremque s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe",
    size: "Larger",
    color: "Black",
    quan: 1,
  },
  {
    id: 14,
    img: "./assets/images/pro6.png",
    name: "MTV Jacket",
    price: 15000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis itaque rerum delenitiiste, excepturi illo! Dolore omnis, eaque nobis cumque assumenda eosprovident unde minus, eligendi delectus id repellat, rationeadipisci ptate saepe s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe",
    size: "X-Larger",
    color: "Black",
    quan: 1,
  },
  {
    id: 15,
    img: "./assets/images/pro7.png",
    name: "Polo Jacket",
    price: 5000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis itaque rerum delenitiiste, excepturi illo! Dolore omnis, eaque nobis cumque assumenda eosprovident unde minus, eligendi delectus id repellat, rationeadipisci rt, rationeadipisci reprehenderit voluptatevoluptate saepe s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe",
    size: "Larger",
    color: "Grey",
    quan: 1,
  },
  {
    id: 16,
    img: "./assets/images/pro8.png",
    name: "Carthartt Pant",
    price: 15000,
    des: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostru    dignissimos possimus quam quis molestiae eveniet nam amet vitaecumque explicabo id debitis quibusdam officiis itaque rerum delenitiiste, excepturi illo! Dolore omnis, eaque nobis cumque assumendt unde minus, eligendi delectus id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe doloremque s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe s id repellat, rationeadipisci reprehenderit voluptatevoluptate saepe",
    size: "Larger",
    color: "Tan",
    quan: 1,
  },
];
